FacilitiesWelfare/urls.py
from django.urls import path
from FacilitiesWelfare.views import *

app_name = "FacilitiesWelfare"
urlpatterns = [
	path('homeFPR', ProjectList.as_view(), name="homeFPR"),
	path('pageFPR/<int:page>', ProjectList.as_view(), name="homeFPR"),
	path('Projects/Create', ProjectCreate.as_view(), name="CreateFPR"),
	path('Projects/delete/<int:pk>', ProjectDelete.as_view(), name="Projects-Delete"),
	path('Projects/update/<int:pk>', ProjectUpdate.as_view(), name="Projects-update"),
	path('homeUFPR', UserProjectListAll.as_view(), name="homeUFPR"),
	path('pageUFPR/<int:page>', UserProjectListAll.as_view(), name="homeUFPR"),
	path('Projects/Projects-Reg-User/<int:pk>', UserRegProject.as_view(), name="Projects-Reg-User"),#User
	path('Projects/Projects-Reg2-User', UserRegProject2.as_view(), name="Projects-Reg2-User"),#User
	path('Projects/Projects-User', UserRegisteryProjects.as_view(), name="Projects-User"),#User
	path('Projects/Projects-User/<int:pk>', UserRegisteryProjects.as_view(), name="Projects-User"),#User
	path('Projects/Projects-Del-User/<int:pk>', ProjectsDelUser.as_view(), name="Projects-Del-User"),#User

	path('homeTFPR', TypeProjectList.as_view(), name="homeTFPR"),
	path('pageTFPR/<int:page>', TypeProjectList.as_view(), name="homeTFPR"),
	path('TypeProjects/CreateT', TypeProjectCreate.as_view(), name="CreateTFPR"),
	path('TypeProjects/delete/<int:pk>', TypeProjectDelete.as_view(), name="TypeProjects-Delete"),
	path('TypeProjects/update/<int:pk>', TypeProjectUpdate.as_view(), name="TypeProjects-update"),

	path('homeFwR', RewardList.as_view(), name="homeFwR"),
	path('pageFwR/<int:page>', RewardList.as_view(), name="homeFwR"),
	path('Reward/CreateR', RewardCreate.as_view(), name="CreateFwR"),
	path('Reward/delete/<int:pk>', RewardDelete.as_view(), name="Reward-Delete"),
	path('Reward/update/<int:pk>', RewardUpdate.as_view(), name="Reward-update"),
	path('Reward/Reward-List-User', UserReward.as_view(), name="Reward-List-User"),#User
	path('Reward/Reward-List-User/<int:page>', UserReward.as_view(), name="Reward-List-User"),#User

	path('homeFwT', TravelsList.as_view(), name="homeFwT"),
	path('pageFwT/<int:page>', TravelsList.as_view(), name="homeFwT"),
	path('Travels/CreateTR', TravelsCreate.as_view(), name="CreateTR"),
	path('Travels/delete/<int:pk>', TravelsDelete.as_view(), name="Travels-Delete"),
	path('Travels/update/<int:pk>', TravelsUpdate.as_view(), name="Travels-update"),
	path('Travels/Travels-List-User', UserTravels.as_view(), name="Travels-List-User"),#User
	path('Travels/Travels-List-User/<int:page>', UserTravels.as_view(), name="Travels-List-User"),#User

	path('homeFwL', LoanList.as_view(), name="homeFwL"),
	path('pageFwL/<int:page>', LoanList.as_view(), name="homeFwL"),
	path('Loan/CreateFwL', LoanCreate.as_view(), name="CreateFwL"),
	path('Loan/delete/<int:pk>', LoanDelete.as_view(), name="Loan-Delete"),
	path('Loan/update/<int:pk>', LoanUpdate.as_view(), name="Loan-update"),

	path('Loan/Loan-List-User', UserLoanList.as_view(), name="Loan-List-User"),
	path('Loan/Loan-List-User/<int:pk>', UserLoanList.as_view(), name="Loan-List-User"),
	path('Loan/Loan-Reg-User/<int:pk>', UserLoanReg.as_view(), name="Loan-Reg-User"),
	path('Loan/Loan-Reg2-User', UserLoanReg2.as_view(), name="Loan-Reg2-User"),
	path('Loan/Loan-List-User2', UserLoanList2.as_view(), name="Loan-List-User2"),
	path('Loan/Loan-List-User2/<int:pk>', UserLoanList2.as_view(), name="Loan-List-User2"),
	path('Loan/Loan-DeleteR-User/<int:pk>', UserLoanDelete.as_view(), name="Loan-DeleteR-User"),

	path('homeRDS', RelativesDeathServicesList.as_view(), name="homeRDS"),
	path('pageRDS/<int:page>', RelativesDeathServicesList.as_view(), name="homeRDS"),
	path('RelativesDeathServices/CreateFwL', RelativesDeathServicesCreate.as_view(), name="CreateRDS"),
	path('RelativesDeathServices/delete/<int:pk>', RelativesDeathServicesDelete.as_view(), name="RelativesDeathServices-Delete"),
	path('RelativesDeathServices/update/<int:pk>', RelativesDeathServicesUpdate.as_view(), name="RelativesDeathServices-update"),
	path('RelativesDeathServices/RelativesDeathServices-List-User', UserRelativesDeathServices.as_view(), name="RelativesDeathServices-List-User"),#User
	path('RelativesDeathServices/RelativesDeathServices-List-User/<int:page>', UserRelativesDeathServices.as_view(), name="RelativesDeathServices-List-User"),#User

	path('homeOH', OrganizationalHouseList.as_view(), name="homeOH"),
	path('pageOH/<int:page>', OrganizationalHouseList.as_view(), name="homeOH"),
	path('OrganizationalHouse/CreateOH', OrganizationalHouseCreate.as_view(), name="CreateOH"),
	path('OrganizationalHouse/delete/<int:pk>', OrganizationalHouseDelete.as_view(), name="OrganizationalHouse-Delete"),
	path('OrganizationalHouse/update/<int:pk>', OrganizationalHouseUpdate.as_view(), name="OrganizationalHouse-update"),
	path('OrganizationalHouse/OrganizationalHouse-List-All', UserOrganizationalHouseListAll.as_view(), name="OrganizationalHouse-List-All"),
	path('OrganizationalHouse/OrganizationalHouse-List-All/<int:pk>', UserOrganizationalHouseListAll.as_view(), name="OrganizationalHouse-List-All"),
	path('OrganizationalHouse/OrganizationalHouse-Reg-User/<int:pk>', OrganizationalHouseRegUser.as_view(), name="OrganizationalHouse-Reg-User"),
	path('OrganizationalHouse/OrganizationalHouse-Reg2-User', OrganizationalHouseRegUser2.as_view(), name="OrganizationalHouse-Reg2-User"),
	path('OrganizationalHouse/OrganizationalHouse-LST-User', OrganizationalHouseListUser.as_view(), name="OrganizationalHouse-LST-User"),
	path('OrganizationalHouse/OrganizationalHouse-LST-User/<int:pk>', OrganizationalHouseListUser.as_view(), name="OrganizationalHouse-LST-User"),

	path('homeROH', RegisterOrganizationalHouseList.as_view(), name="homeROH"),
	path('pageROH/<int:page>', RegisterOrganizationalHouseList.as_view(), name="homeROH"),
	path('RegisterOrganizationalHouse/CreateROH', RegisterOrganizationalHouseCreate.as_view(), name="CreateROH"),
	path('RegisterOrganizationalHouse/delete/<int:pk>', RegisterOrganizationalHouseDelete.as_view(), name="RegisterOrganizationalHouse-Delete"),
	path('RegisterOrganizationalHouse/update/<int:pk>', RegisterOrganizationalHouseUpdate.as_view(), name="RegisterOrganizationalHouse-update"),

	path('homeSAV', SeeAndVisitList.as_view(), name="homeSAV"),
	path('pageSAV/<int:page>', SeeAndVisitList.as_view(), name="homeSAV"),
	path('SeeAndVisit/CreateSAV', SeeAndVisitCreate.as_view(), name="CreateSAV"),
	path('SeeAndVisit/delete/<int:pk>', SeeAndVisitDelete.as_view(), name="SeeAndVisit-Delete"),
	path('SeeAndVisit/update/<int:pk>', SeeAndVisitUpdate.as_view(), name="SeeAndVisit-update"),
	path('SeeAndVisit/SeeAndVisit-List-User', SeeAndVisitUser.as_view(), name="SeeAndVisit-List-User"),#User
	path('SeeAndVisit/SeeAndVisit-List-User/<int:page>', SeeAndVisitUser.as_view(), name="SeeAndVisit-List-User"),#User

	path('homeCA', CashAssistanceList.as_view(), name="homeCA"),
	path('pageCA/<int:page>', CashAssistanceList.as_view(), name="homeCA"),
	path('CashAssistance/CreateCA', CashAssistanceCreate.as_view(), name="CreateCA"),
	path('CashAssistance/delete/<int:pk>', CashAssistanceDelete.as_view(), name="CashAssistance-Delete"),
	path('CashAssistance/update/<int:pk>', CashAssistanceUpdate.as_view(), name="CashAssistance-update"),
	path('CashAssistance/CashAssistance-List-User', UserCashAssistance.as_view(), name="CashAssistance-List-User"),#User
	path('CashAssistance/CashAssistance-List-User/<int:page>', UserCashAssistance.as_view(), name="CashAssistance-List-User"),#User

	path('homeCI', ConsumerItemsList.as_view(), name="homeCI"),
	path('pageCI/<int:page>', ConsumerItemsList.as_view(), name="homeCI"),
	path('ConsumerItems/CreateCI', ConsumerItemsCreate.as_view(), name="CreateCI"),
	path('ConsumerItems/delete/<int:pk>', ConsumerItemsDelete.as_view(), name="ConsumerItems-Delete"),
	path('ConsumerItems/update/<int:pk>', ConsumerItemsUpdate.as_view(), name="ConsumerItems-update"),
	path('ConsumerItems/ConsumerItems-List-User', UserConsumerItems.as_view(), name="ConsumerItems-List-User"),#User
	path('ConsumerItems/ConsumerItems-List-User/<int:page>', UserConsumerItems.as_view(), name="ConsumerItems-List-User"),#User

	path('homeCIR', ConsumerItemsRegisterList.as_view(), name="homeCIR"),
	path('pageCIR/<int:page>', ConsumerItemsRegisterList.as_view(), name="homeCIR"),
	path('ConsumerItemsRegister/CreateCIR', ConsumerItemsRegisterCreate.as_view(), name="CreateCIR"),
	path('ConsumerItemsRegister/delete/<int:pk>', ConsumerItemsRegisterDelete.as_view(), name="ConsumerItemsRegister-Delete"),
	path('ConsumerItemsRegisterUser/delete/<int:pk>', ConsumerItemsRegisterUserDelete.as_view(), name="ConsumerItemsRegister-User-Delete"),
	path('ConsumerItemsRegister/update/<int:pk>', ConsumerItemsRegisterUpdate.as_view(), name="ConsumerItemsRegister-update"),
	path('ConsumerItemsRegister/ConsumerItemsRegister-List-User', UserConsumerItemsRegister.as_view(), name="ConsumerItemsRegister-List-User"),#User
	path('ConsumerItemsRegister/ConsumerItemsRegister-List-User/<int:page>', UserConsumerItemsRegister.as_view(), name="ConsumerItemsRegister-List-User"),#User
	path('ConsumerItemsRegister/ConsumerItemsRegister-Reg-User/<int:pk>', UserRegisterConsumerItems.as_view(), name="ConsumerItemsRegister-Reg-User"),#User
	path('ConsumerItemsRegister/ConsumerItemsRegister-Reg2-User', UserRegisterConsumerItems2.as_view(), name="ConsumerItemsRegister-Reg2-User"),#User

	path('homeFH', FreeHelpList.as_view(), name="homeFH"),
	path('pageFH/<int:page>', FreeHelpList.as_view(), name="homeFH"),
	path('FreeHelp/CreateFH', FreeHelpCreate.as_view(), name="CreateFH"),
	path('FreeHelp/delete/<int:pk>', FreeHelpDelete.as_view(), name="FreeHelp-Delete"),
	path('FreeHelp/update/<int:pk>', FreeHelpUpdate.as_view(), name="FreeHelp-update"),
	path('FreeHelp/FreeHelp-List-User', UserFreeHelp.as_view(), name="FreeHelp-List-User"),#User
	path('FreeHelp/FreeHelp-List-User/<int:page>', UserFreeHelp.as_view(), name="FreeHelp-List-User"),#User

blog/urls.py
from django.urls import path
from .views import (
	ArticleList,
	ArticleDetail,
	ArticlePreview,
	CategoryList,
	AuthorList,
	SearchList
)

app_name = "blog"
urlpatterns = [
	path('', ArticleList.as_view(), name="home"),
	path('page/<int:page>', ArticleList.as_view(), name="home"),
	path('article/<slug:slug>', ArticleDetail.as_view(), name="detail"),
	path('preview/<int:pk>', ArticlePreview.as_view(), name="preview"),
	path('category/<slug:slug>', CategoryList.as_view(), name="category"),
	path('category/<slug:slug>/page/<int:page>', CategoryList.as_view(), name="category"),
	path('author/<slug:username>', AuthorList.as_view(), name="author"),
	path('author/<slug:username>/page/<int:page>', AuthorList.as_view(), name="author"),
	path('search/', SearchList.as_view(), name="search"),
	path('search/page/<int:page>', SearchList.as_view(), name="search"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from account.views import Login, Register, activate

urlpatterns = [
    path('', include('blog.urls')),
    path('', include('django.contrib.auth.urls')),
    path('login/', Login.as_view(), name='login'),
    path('register/', Register.as_view(), name='register'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', activate, name='activate'),
    re_path(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
    path('account/', include('account.urls')),
    path('admin/', admin.site.urls),
    path('comment/', include('comment.urls')),
    path('inventory/', include('inventory.urls')),
    path('FacilitiesWelfare/', include('FacilitiesWelfare.urls')),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FacilitiesWelfare/models/CashAssistance.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from extensions.utils import jalali_converter,jalali_converterWT
import humanize

class CashAssistance(models.Model):
    TypeAssistance = (
        ('PU', "همگانی"),
        ('PR', "خاص"),
    )
    Id = models.AutoField(unique=True, primary_key=True, verbose_name="شناسه")
    Title = models.CharField(max_length=200, verbose_name="عنوان")
    TypeAssistance = models.CharField(max_length=2, choices=TypeAssistance, default="PU", verbose_name="نوع کمک")
    IdUser = models.ForeignKey(get_user_model(),on_delete=models.CASCADE,verbose_name="شناسه کاربر",blank=True,null=True)
    Price = models.IntegerField(verbose_name="مبلغ کمک",default=0)
    DateRegister = models.DateTimeField(verbose_name="تاریخ ثبت کمک معیشتی")#تاریخ ثبت کمک
    Description = models.TextField(verbose_name="توضیحات")

    def HPrice(self):
        return humanize.intcomma(self.Price)
    HPrice.short_description = "مبلغ"

    def jDateRegister(self):
        return jalali_converterWT(self.DateRegister)
    jDateRegister.short_description = "تاریخ ثبت کمک معیشتی"

    def __str__(self):
        self.Title

    class Meta:
        verbose_name = 'کمک معیشتی نقدی'
        verbose_name_plural = 'کمک های معیشتی'

FacilitiesWelfare/views/Assistance.py
from django.shortcuts import render
from account.mixins import (
	FieldsMixin,
	FormValidMixin,
	AuthorAccessMixin,
	AuthorsAccessMixin,
	SuperUserAccessMixin,
    FacilitiesWelfareAccessMixin
)
from django.views.generic import (
	ListView,
	CreateView,
	UpdateView,
	DeleteView,
    DetailView
)
from django.urls import reverse_lazy
from extensions.utils import jalali_converter
from django.shortcuts import render, get_object_or_404
from FacilitiesWelfare.models import *
from FacilitiesWelfare.forms import *

class AssistanceList(FacilitiesWelfareAccessMixin,ListView):
    login_url = '/login/'
    model = Assistance
    paginate_by = 10
    template_name = "FacilitiesWelfare/Assistance/Assistance_list.html"

    def get_queryset(self):
        return Assistance.objects.all()

    def get_object(self):
        return User.objects.get(pk = self.request.user.pk)

    def get_form_kwargs(self):
        kwargs = super(Assistance, self).get_form_kwargs()
        kwargs.update({
            'user': self.request.user
        })
        return kwargs

class AssistanceCreate(FacilitiesWelfareAccessMixin,DefineAssistance,CreateView):
    model = Assistance
    success_url = reverse_lazy('FacilitiesWelfare:homeASis')
    template_name = "FacilitiesWelfare/Assistance/Assistance-create-update.html"

class AssistanceUpdate(FacilitiesWelfareAccessMixin,DefineAssistance,UpdateView):
    model = Assistance
    success_url = reverse_lazy('FacilitiesWelfare:homeASis')
    template_name = "FacilitiesWelfare/Assistance/Assistance-create-update.html"

class AssistanceDelete(FacilitiesWelfareAccessMixin,DeleteView):
    model = Assistance
    success_url = reverse_lazy('FacilitiesWelfare:homeASis')
    template_name = "FacilitiesWelfare/Assistance/Assistance_confirm_delete.html"

FacilitiesWelfare/views/CashAssistance.py
from django.shortcuts import render
from account.mixins import (
	FieldsMixin,
	FormValidMixin,
	AuthorAccessMixin,
	AuthorsAccessMixin,
	SuperUserAccessMixin,
    FacilitiesWelfareAccessMixin
)
from django.views.generic import (
	ListView,
	CreateView,
	UpdateView,
	DeleteView,
    DetailView
)
from django.urls import reverse_lazy
from extensions.utils import jalali_converter
from django.shortcuts import render, get_object_or_404
from FacilitiesWelfare.models import *
from FacilitiesWelfare.forms import *
from django.contrib.auth.mixins import LoginRequiredMixin

class CashAssistanceList(FacilitiesWelfareAccessMixin,ListView):
    login_url = '/login/'
    model = CashAssistance
    paginate_by = 10
    template_name = "FacilitiesWelfare/CashAssistance/CashAssistance_list.html"

    def get_queryset(self):
        return CashAssistance.objects.all()

    def get_object(self):
        return User.objects.get(pk = self.request.user.pk)

    def get_form_kwargs(self):
        kwargs = super(CashAssistance, self).get_form_kwargs()
        kwargs.update({
            'user': self.request.user
        })
        return kwargs

class CashAssistanceCreate(FacilitiesWelfareAccessMixin,DefineCachAssistance,CreateView):
    model = CashAssistance
    success_url = reverse_lazy('FacilitiesWelfare:homeCA')
    template_name = "FacilitiesWelfare/CashAssistance/CashAssistance-create-update.html"

class CashAssistanceUpdate(FacilitiesWelfareAccessMixin,DefineCachAssistance,UpdateView):
    model = CashAssistance
    success_url = reverse_lazy('FacilitiesWelfare:homeCA')
    template_name = "FacilitiesWelfare/CashAssistance/CashAssistance-create-update.html"

class CashAssistanceDelete(FacilitiesWelfareAccessMixin,DeleteView):
    model = CashAssistance
    success_url = reverse_lazy('FacilitiesWelfare:homeCA')
    template_name = "FacilitiesWelfare/CashAssistance/CashAssistance_confirm_delete.html"

class UserCashAssistance(LoginRequiredMixin,ListView):
    login_url = '/login/'
    model = CashAssistance
    paginate_by = 10
    template_name = "FacilitiesWelfare/CashAssistance/CashAssistance_list_User.html"

    def get_queryset(self):
        return CashAssistance.objects.filter(Q(IdUser=self.request.user) | Q(TypeAssistance="PU")).order_by("TypeAssistance")

    def get_object(self):
        return CashAssistance.objects.get(pk = self.request.user.pk)

templates/FacilitiesWelfare/Projects/Projects-create-update.html
{% extends 'Template/base.html' %}
{% load crispy_forms_tags %}

{% block title %}{% block title-meta %}
	پروژه جدید
{% endblock %}{% endblock %}

{% block main %}
<div class="col-md-12">
	<div class="card card-primary">
		<div class="card-header">
			<h3 class="card-title mb-0 float-left">افزودن پروژه</h3>
		</div>
		<div class="card-body">
			<form method="post" enctype="multipart/form-data">{% csrf_token %}
				<div class="row">
					<div class="col-sm-4 col-md-4 col-lg-3">
						{{ form.Name|as_crispy_field }}
					</div>
					<div class="col-sm-4 col-md-4 col-lg-3">
						{{ form.IdCity|as_crispy_field }}
					</div>
					<div class="col-sm-4 col-md-4 col-lg-3">
						{{ form.IdTypeProject|as_crispy_field }}
					</div>
					<div class="col-12">
						{{ form.Description|as_crispy_field }}
					</div>
				</div>
				<button class="btn btn-success">ثبت پروژه</button>
				{% if user.is_superuser and item.pk %}
				<a class="badge text-danger" href="{% url 'FacilitiesWelfare:Projects-Delete' item.pk %}">حذف</a>
				{% endif %}
			</form>
		</div>
</div>
{% endblock %}

templates/FacilitiesWelfare/Projects/Projects_User_Registry.html
{% extends 'Template/base.html' %}

{% block title %}{% block title-meta %}
	لیست پروژه ها
{% endblock %}{% endblock %}


{% block Create %}
    <span class="badge text-primary"">لیست پروژه های شما</span>
{% endblock %}

{% block main %}
    {% if object_list %}
    <table class="tableResponse">
        <thead>
            <tr>
                <th>نام پروژه</th>
                <th>شهر</div>
                <th>نوع پروژه</th>
                <th>توضیحات</th>
                <th>لغو درخواست</th>
            </tr>
        </thead>
        {% for item in object_list %}
        <tbody>
            <tr>
                <td data-label="نام پروژه">{{item.IdProject.Name}}</td>
                <td data-label="شهر">{{item.IdProject.IdCity}}</td>
                <td data-label="نوع پروژه">{{item.IdProject.IdTypeProject.Name}}</td>
                <td data-label="توضیحات">{{item.IdProject.Description|safe}}</td>
                <td data-label="لغو درخواست">
                    <a class="badge text-succsess" href="{% url 'FacilitiesWelfare:Projects-Del-User' item.pk %}">لغو درخواست</a>
                </td>
            </tr>
        </tbody>
        {% endfor %}
    </table>
    <div class="row pagination">
        <span class="step-links">
            {% if is_paginated %}
                {% if page_obj.has_previous %}
                    <a class="btn btn-primary" href="{% url 'FacilitiesWelfare:Projects-User' page_obj.previous_page_number %}">
                        قبلی
                    </a>
                {% endif %}
                {% if page_obj.has_next %}
                    <a class="btn btn-primary" href="{% url 'FacilitiesWelfare:Projects-User' page_obj.next_page_number %}">
                        بعدی
                    </a>
                {% endif %}
            {% endif %}
        </span>
    </div>
    {% else %}
    <div style="min-height:200px;">
        <P class="text-center">
            لیست پروژه ها خالی است
            <br>
        </P>
    </div>
    {% endif %}
{% endblock %}

templates/FacilitiesWelfare/Projects/Projects_list.html
{% extends 'Template/base.html' %}

{% block title %}{% block title-meta %}
	لیست پروژه ها
{% endblock %}{% endblock %}


{% block Create %}
    <a class="badge text-primary" href="{% url 'FacilitiesWelfare:CreateFPR' %}">تعریف پروژه</a>
{% endblock %}

{% block main %}
    {% if object_list %}
    <table class="tableResponse">
        <thead>
            <tr>
                <th>نام پروژه</th>
                <th>شهر</div>
                <th>نوع پروژه</th>
                <th>توضیحات</th>
                <th>عملیات</th>
            </tr>
        </thead>
        {% for item in object_list %}
        <tbody>
            <tr>
                <td data-label="نام پروژه">{{item.Name}}</td>
                <td data-label="شهر">{{item.IdCity}}</td>
                <td data-label="نوع پروژه">{{item.IdTypeProject}}</td>
                <td data-label="توضیحات">{{item.Description|safe}}</td>
                <td data-label="عملیات">
                    {% if user.is_superuser or user.is_FacilitiesWelfare %}
                    <a class="badge text-danger" href="{% url 'FacilitiesWelfare:Projects-Delete' item.pk %}">حذف</a>
                    <a class="badge text-succsess" href="{% url 'FacilitiesWelfare:Projects-update' item.pk %}">ویرایش</a>
                    {% endif %}
                </td>
            </tr>
        </tbody>
        {% endfor %}
    </table>
    <div class="row pagination">
        <span class="step-links">
            {% if is_paginated %}
                {% if page_obj.has_previous %}
                    <a class="btn btn-primary" href="{% url 'FacilitiesWelfare:homeFPR' page_obj.previous_page_number %}">
                        قبلی
                    </a>
                {% endif %}
                {% if page_obj.has_next %}
                    <a class="btn btn-primary" href="{% url 'FacilitiesWelfare:homeFPR' page_obj.next_page_number %}">
                        بعدی
                    </a>
                {% endif %}
            {% endif %}
        </span>
    </div>
    {% else %}
    <div style="min-height:200px;">
        <P class="text-center">
            لیست پروژه ها خالی است
            <br>
            <a href="{% url 'FacilitiesWelfare:CreateFPR' %}">
                تعریف پروژه
            </a>
        </P>
    </div>
    {% endif %}
{% endblock %}

templates/FacilitiesWelfare/Projects/TypeProjects_list.html
{% extends 'Template/base.html' %}

{% block title %}{% block title-meta %}
	نوع پروژه ها
{% endblock %}{% endblock %}


{% block Create %}
    <a class="badge text-primary" href="{% url 'FacilitiesWelfare:CreateTFPR' %}">تعریف نوع پروژه</a>
{% endblock %}

{% block main %}
    {% if object_list %}
    <table class="tableResponse">
        <thead>
            <tr>
                <th>شناسه</th>
                <th>نوع پروژه</th>
                <th>عملیات</th>
            </tr>
        </thead>
        <tbody>
        {% for item in object_list %}
            <tr>
                <td data-label="شناسه">{{item.Id}}</td>
                <td data-label="نوع پروژه">{{item.Name}}</td>
                <td data-label="عملیات">
                    {% if user.is_superuser or user.is_FacilitiesWelfare %}
                    <a class="badge text-danger" href="{% url 'FacilitiesWelfare:TypeProjects-Delete' item.pk %}">حذف</a>
                    <a class="badge text-succsess" href="{% url 'FacilitiesWelfare:TypeProjects-update' item.pk %}">ویرایش</a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="row pagination">
        <span class="step-links">
            {% if is_paginated %}
                {% if page_obj.has_previous %}
                    <a class="btn btn-primary" href="{% url 'FacilitiesWelfare:homeTFPR' page_obj.previous_page_number %}">
                        قبلی
                    </a>
                {% endif %}
                {% if page_obj.has_next %}
                    <a class="btn btn-primary" href="{% url 'FacilitiesWelfare:homeTFPR' page_obj.next_page_number %}">
                        بعدی
                    </a>
                {% endif %}
            {% endif %}
        </span>
    </div>
    {% else %}
    <div style="min-height:200px;">
        <P class="text-center">
            نوع پروژه ها خالی است
            <br>
            <a href="{% url 'FacilitiesWelfare:CreateTFPR' %}">
                تعریف نوع پروژه
            </a>
        </P>
    </div>
    {% endif %}
{% endblock %}