blog/urls.py
from django.urls import path
from .views import (
	ArticleList,
	ArticleDetail,
	ArticlePreview,
	CategoryList,
	AuthorList,
	SearchList
)

app_name = "blog"
urlpatterns = [
	path('', ArticleList.as_view(), name="home"),
	path('page/<int:page>', ArticleList.as_view(), name="home"),
	path('article/<slug:slug>', ArticleDetail.as_view(), name="detail"),
	path('preview/<int:pk>', ArticlePreview.as_view(), name="preview"),
	path('category/<slug:slug>', CategoryList.as_view(), name="category"),
	path('category/<slug:slug>/page/<int:page>', CategoryList.as_view(), name="category"),
	path('author/<slug:username>', AuthorList.as_view(), name="author"),
	path('author/<slug:username>/page/<int:page>', AuthorList.as_view(), name="author"),
	path('search/', SearchList.as_view(), name="search"),
	path('search/page/<int:page>', SearchList.as_view(), name="search"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from account.views import Login, Register, activate

urlpatterns = [
    path('', include('blog.urls')),
    path('', include('django.contrib.auth.urls')),
    path('login/', Login.as_view(), name='login'),
    path('register/', Register.as_view(), name='register'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', activate, name='activate'),
    re_path(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
    path('account/', include('account.urls')),
    path('admin/', admin.site.urls),
    path('comment/', include('comment.urls')),
    path('inventory/', include('inventory.urls')),
    path('FacilitiesWelfare/', include('FacilitiesWelfare.urls')),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inventory/urls.py
from django.urls import path
from .views import (
	StoreroomList,StoreroomCreate,StoreroomDelete,StoreroomUpdate,
	GroupCommodityList,GroupCommodityCreate,GroupCommodityDelete,GroupCommodityUpdate,
	CategoryCommodityList,CategoryCommodityCreate,CategoryCommodityDelete,CategoryCommodityUpdate,
	UnitPackList,UnitPackCreate,UnitPackDelete,UnitPackUpdate,
	SupplierList,SupplierCreate,SupplierDelete,SupplierUpdate,
	UnitofMeasurementList,UnitofMeasurementCreate,UnitofMeasurementDelete,UnitofMeasurementUpdate,
	CommodityList,CommodityCreate,CommodityDelete,CommodityUpdate,
	CustomerList,CustomerCreate,CustomerDelete,CustomerUpdate,
	driversList,driversCreate,driversDelete,driversUpdate,
	EntryCommodityList,EntryCommodityCreate,EntryCommodityDelete,EntryCommodityUpdate,
	TransportationList,TransportationCreate,TransportationDelete,TransportationUpdate,
	ProductRepairedList,ProductRepairedCreate,ProductRepairedUpdate,ProductRepairedDelete,
	ReceiptList,ReceiptCreate,ReceiptUpdate,ReceiptDelete,
	SettlementArrivedList,SettlementArrivedCreate,SettlementArrivedUpdate,SettlementArrivedDelete,
	PurchaseRequestList,PurchaseRequestCreate,PurchaseRequestUpdate,PurchaseRequestDelete,
	storeroomList,StoreroomListReport,SupplierListReport,PurchaseRequestListReport,PurchaseRequestListSRReport,CommodityListReport,CommodityAllListReport,CustomerListReport,DriversReport,ReceiptReportBuy,ReceiptReportSale,ReceiptReportStoreroomSale,ReceiptReportStoreroomBuy,ProductPerStoreroom,EntryCommodityReport,
	Dashboard,CommodityPriceByStoreroom,PurchaseBuyNPriceByStoreroom,PurchaseBuyYPriceByStoreroom
)

app_name = "inventory"
urlpatterns = [
	path('d', CommodityPriceByStoreroom.as_view(), name="d"),
	path('d1', PurchaseBuyNPriceByStoreroom.as_view(), name="d1"),
	path('d2', PurchaseBuyYPriceByStoreroom.as_view(), name="d2"),
	
	path('Dashboard', Dashboard.as_view(), name="Dashboard"),

	path('homeSL', StoreroomList.as_view(), name="homeSL"),
	path('page/<int:page>', StoreroomList.as_view(), name="homeSL"),
	path('inventory/Create', StoreroomCreate.as_view(), name="Create"),
	path('inventory/delete/<int:pk>', StoreroomDelete.as_view(), name="Storeroom-Delete"),
	path('inventory/update/<int:pk>', StoreroomUpdate.as_view(), name="Storeroom-update"),
	path('StoreroomListReport/<int:IdStoreroom>',StoreroomListReport.as_view(),name="StoreroomListReport"),

	path('homeGC', GroupCommodityList.as_view(), name="homeGC"),
	path('pageGC/<int:page>', GroupCommodityList.as_view(), name="homeGC"),
	path('GroupCommodity/Create', GroupCommodityCreate.as_view(), name="GroupCommodity-Create"),
	path('GroupCommodity/delete/<int:pk>', GroupCommodityDelete.as_view(), name="GroupCommodity-Delete"),
	path('GroupCommodity/update/<int:pk>', GroupCommodityUpdate.as_view(), name="GroupCommodity-update"),

	path('homeCC', CategoryCommodityList.as_view(), name="homeCC"),
	path('pageCC/<int:page>', CategoryCommodityList.as_view(), name="homeCC"),
	path('CategoryCommodity/Create', CategoryCommodityCreate.as_view(), name="CategoryCommodity-Create"),
	path('CategoryCommodity/delete/<int:pk>', CategoryCommodityDelete.as_view(), name="CategoryCommodity-Delete"),
	path('CategoryCommodity/update/<int:pk>', CategoryCommodityUpdate.as_view(), name="CategoryCommodity-update"),

	path('homeUP', UnitPackList.as_view(), name="homeUP"),
	path('pageUP/<int:page>', UnitPackList.as_view(), name="homeUP"),
	path('UnitPack/Create', UnitPackCreate.as_view(), name="UnitPack-Create"),
	path('UnitPack/delete/<int:pk>', UnitPackDelete.as_view(), name="UnitPack-Delete"),
	path('UnitPack/update/<int:pk>', UnitPackUpdate.as_view(), name="UnitPack-update"),

	path('homeSU', SupplierList.as_view(), name="homeSU"),
	path('pageSU/<int:page>', SupplierList.as_view(), name="homeSU"),
	path('Supplier/Create', SupplierCreate.as_view(), name="Supplier-Create"),
	path('Supplier/delete/<int:pk>', SupplierDelete.as_view(), name="Supplier-Delete"),
	path('Supplier/update/<int:pk>', SupplierUpdate.as_view(), name="Supplier-update"),
	path('SupplierListReport/<int:IdSupplier>',SupplierListReport.as_view(),name="SupplierListReport"),

	path('homeUM', UnitofMeasurementList.as_view(), name="homeUM"),
	path('pageUM/<int:page>', UnitofMeasurementList.as_view(), name="homeUM"),
	path('UnitofMeasurement/Create', UnitofMeasurementCreate.as_view(), name="UnitofMeasurement-Create"),
	path('UnitofMeasurement/delete/<int:pk>', UnitofMeasurementDelete.as_view(), name="UnitofMeasurement-Delete"),
	path('UnitofMeasurement/update/<int:pk>', UnitofMeasurementUpdate.as_view(), name="UnitofMeasurement-update"),

	path('homeCO', CommodityList.as_view(), name="homeCO"),
	path('pageCO/<int:page>', CommodityList.as_view(), name="homeCO"),
	path('Commodity/Create', CommodityCreate.as_view(), name="Commodity-Create"),
	path('Commodity/delete/<int:pk>', CommodityDelete.as_view(), name="Commodity-Delete"),
	path('Commodity/update/<int:pk>', CommodityUpdate.as_view(), name="Commodity-update"),
	path('CommodityListReport/<int:IdCommodity>', CommodityListReport.as_view(), name="Commodity-Report"),
	path('CommodityAllListReport/', CommodityAllListReport.as_view(), name="CommodityAll-Report"),

	path('homeCU', CustomerList.as_view(), name="homeCU"),
	path('pageCU/<int:page>', CustomerList.as_view(), name="homeCU"),
	path('Customer/Create', CustomerCreate.as_view(), name="Customer-Create"),
	path('Customer/delete/<int:pk>', CustomerDelete.as_view(), name="Customer-Delete"),
	path('Customer/update/<int:pk>', CustomerUpdate.as_view(), name="Customer-update"),
	path('CustomerReport/', CustomerListReport.as_view(), name="Customer-Report"),

	path('homeDL', driversList.as_view(), name="homeDL"),
	path('pageDL/<int:page>', driversList.as_view(), name="homeDL"),
	path('drivers/Create', driversCreate.as_view(), name="drivers-Create"),
	path('drivers/delete/<int:pk>', driversDelete.as_view(), name="drivers-Delete"),
	path('drivers/update/<int:pk>', driversUpdate.as_view(), name="drivers-update"),
	path('DriversReport', DriversReport.as_view(), name="Drivers-Report"),

	path('homeEC', EntryCommodityList.as_view(), name="homeEC"),
	path('pageEC/<int:page>', EntryCommodityList.as_view(), name="homeEC"),
	path('EntryCommodity/Create', EntryCommodityCreate.as_view(), name="EntryCommodity-Create"),
	path('EntryCommodity/delete/<int:pk>', EntryCommodityDelete.as_view(), name="EntryCommodity-Delete"),
	path('EntryCommodity/update/<int:pk>', EntryCommodityUpdate.as_view(), name="EntryCommodity-update"),
	path('EntryCommodityReport/<int:IdStoreroom>/<int:Type>', EntryCommodityReport.as_view(), name="EntryCommodity-Report"),

	path('homeTP', TransportationList.as_view(), name="homeTP"),
	path('pageTP/<int:page>', TransportationList.as_view(), name="homeTP"),
	path('Transportation/Create', TransportationCreate.as_view(), name="Transportation-Create"),
	path('Transportation/delete/<int:pk>', TransportationDelete.as_view(), name="Transportation-Delete"),
	path('Transportation/update/<int:pk>', TransportationUpdate.as_view(), name="Transportation-update"),

	path('homePR', ProductRepairedList.as_view(), name="homePR"),
	path('pagePR/<int:page>', ProductRepairedList.as_view(), name="homePR"),
	path('productRepaired/Create', ProductRepairedCreate.as_view(), name="productRepaired-Create"),
	path('productRepaired/delete/<int:pk>', ProductRepairedDelete.as_view(), name="productRepaired-Delete"),
	path('productRepaired/update/<int:pk>', ProductRepairedUpdate.as_view(), name="productRepaired-update"),
	path('ProductPerStoreroom/<int:IdStoreroom>', ProductPerStoreroom.as_view(), name="ProductPerStoreroom-Report"),

	path('homeRE', ReceiptList.as_view(), name="homeRE"),
	path('pageRE/<int:page>', ReceiptList.as_view(), name="homeRE"),
	path('Receipt/Create', ReceiptCreate.as_view(), name="Receipt-Create"),
	path('Receipt/delete/<int:pk>', ReceiptDelete.as_view(), name="Receipt-Delete"),
	path('Receipt/update/<int:pk>', ReceiptUpdate.as_view(), name="Receipt-update"),
	path('ReportBuy', ReceiptReportBuy.as_view(), name="Receipt-ReportBuy"),
	path('ReportSale', ReceiptReportSale.as_view(), name="Receipt-ReportSale"),
	path('ReportStoreroomBuy/<int:IdStoreroom>', ReceiptReportStoreroomBuy.as_view(), name="Receipt-ReportStoreroomBuy"),
	path('ReportStoreroomSale/<int:IdStoreroom>', ReceiptReportStoreroomSale.as_view(), name="Receipt-ReportStoreroomSale"),
	

	path('homeSA', SettlementArrivedList.as_view(), name="homeSA"),
	path('pageSA/<int:page>', SettlementArrivedList.as_view(), name="homeSA"),
	path('SettlementArrived/Create', SettlementArrivedCreate.as_view(), name="SettlementArrived-Create"),
	path('SettlementArrived/delete/<int:pk>', SettlementArrivedDelete.as_view(), name="SettlementArrived-Delete"),
	path('SettlementArrived/update/<int:pk>', SettlementArrivedUpdate.as_view(), name="SettlementArrived-update"),

	path('homePPR', PurchaseRequestList.as_view(), name="homePPR"),
	path('pagePPR/<int:page>', PurchaseRequestList.as_view(), name="homePPR"),
	path('PurchaseRequest/Create', PurchaseRequestCreate.as_view(), name="PurchaseRequest-Create"),
	path('PurchaseRequest/delete/<int:pk>', PurchaseRequestDelete.as_view(), name="PurchaseRequest-Delete"),
	path('PurchaseRequest/update/<int:pk>', PurchaseRequestUpdate.as_view(), name="PurchaseRequest-update"),
	path('PurchaseRequest/<int:IdCommodity>', PurchaseRequestListReport.as_view(), name="PurchaseRequest-Report"),
	path('PurchaseRequestSR/<int:IdStoreroom>', PurchaseRequestListSRReport.as_view(), name="PurchaseRequestSR-Report"),
]

inventory/forms.py
from django import forms
from inventory.models import (
	Storeroom,
	GroupCommodity,
	drivers,
	Commodity,
	Customer,
	UnitofMeasurement,
	UnitPack,
	Supplier,
	EntryCommodity,
	Transportation,
	productRepaired,
	TransfersbetweenStoreroom,
	Receipt,
	SettlementArrived,
	PurchaseRequest
	)

class DefineStoreroom(forms.ModelForm):
	class Meta:
		model = Storeroom
		fields = ['Id','Name', 'IdCity', 'Address','status','Telephone']

class DefineGroupCommodity(forms.ModelForm):
	class Meta:
		model = GroupCommodity
		fields = ['Id', 'Name']

class Definedrivers(forms.ModelForm):
	class Meta:
		model = drivers
		fields = ['DriverCode','Name','Family','Telephone','NationalCode','LicensePlateNumber','CarType',
				  'FreightName','AccountNumber','Shabanumber','CardNumber','Address','Description']

class DefinedCommodity(forms.ModelForm):
	class Meta:
		model = Commodity
		fields = [
			'Id','IdStoreroom','Name','IdGroup','IdCategory','IdUnitPack',
			'UnitPackCount','CommoditySpecifications','ExpirationDate',
			'IdSupplier','IdUnitofMeasurement','OrderPoint','MinimumInventory',
			'OrderAmount','MaximumInventory','AddressCommodity','TechnicalNumber','BarCodeText',
			'BarCodeImage','TechnicalSpecifications','UnitPrice','Description',
		]

class DefinedCustomer(forms.ModelForm):
	class Meta:
		model = Customer
		fields = [
			'AccountSideCode','Name','Family',
			'Mobile','TelephoneCustomer','RegistrationNumber',
			'FirstBalanceCourse','EconomicNumber','Status',
			'NationalID','PostalCode','Address'
		]

class DefinedGroupCommodity(forms.ModelForm):
	class Meta:
		model = GroupCommodity
		fields = [
			'Id', 'Name',
		]

class DefinedUnitofMeasurement(forms.ModelForm):
	class Meta:
		model = UnitofMeasurement
		fields = [
			'Id', 'Name',
		]

class DefinedUnitPack(forms.ModelForm):
	class Meta():
		model = UnitPack
		fields = [
			'Id', 'Name',
		]

class DefinedSupplier(forms.ModelForm):
	class Meta:
		model = Supplier
		fields = [
			'Id', 'Name',
		]

class DefinedEntryCommodity(forms.ModelForm):
	class Meta:
		model = EntryCommodity
		fields = [
			'Id', 'IdCommodity','Status','IdStoreroom','Count','DateEntry','Description','IdCustomer','Serial','DateExpired'
		]

class DefinedTransportation(forms.ModelForm):
	class Meta:
		model = Transportation
		fields = ['Id','IdDrivers','Sender','FreightNumber','Transferee','SourceAddress','Description','IdEntryCommodity']

class DefinedProductRepaired(forms.ModelForm):
	class Meta:
		model = productRepaired
		fields = ['Id','IdCommodity','IdCustomer','SerialNumber','DateDelivery','Description','IdStoreroom','Status']

class DefinedTransfersbetweenStoreroom(forms.ModelForm):
	class Meta:
		model = TransfersbetweenStoreroom
		fields = ['Id','IdStoreroomSource','IdStoreroomDestination','Description']

class DefinedReceipt(forms.ModelForm):
	class Meta:
		model = Receipt
		fields = ['Id','IdCommodity','IdStoreroom','IdUnitofMeasurement','Count','Amount','Discount','Taxation','IdCustomer','Type']

class DefinedSettlementArrived(forms.ModelForm):
	class Meta:
		model = SettlementArrived
		fields = ['Id','Type','Amount','Description','Address','Telephone','ReceiptNumber','IdStoreroom']

class DefinedPurchaseRequest(forms.ModelForm):
	class Meta:
		model = PurchaseRequest
		fields = ['Id','IdCommodity','IdUnitofMeasurement','Count','DateRequired','IdStoreroom','TechnicalSpecifications','PurchaseSource','PurchasingOfficer','Status']

templates/inventory/Receipt/ListBuy.html
{% extends 'Template/base.html' %}
{% load humanize %}

{% block title %}{% block title-meta %}
	لیست فاکتور خرید
{% endblock %}{% endblock %}

{% block Css %}
    <link rel="stylesheet" href="https://cdn.rtlcss.com/bootstrap/v4.2.1/css/bootstrap.min.css">
    <style type="text/css">
    *{
        direction:rtl;
    }
    .SPNName{
        color:rgb(71, 67, 67);
        text-decoration: underline;
    }
    @media print{
        button,h2,.main-footer{
            display: none !important;
        }
    }
    </style>
{% endblock %}
{% block JS %}
    <!-- <script type="text/javascript">
        window.onload = print();
    </script> -->
{% endblock %}
{% block main %}
{% if ReceiptBuy %}
    <table class="tableResponse">
        <thead>
            <tr>
                <td>ردیف</td>
                <td>کالا</td>
                <td>واحد سنجش</td>
                <td>تعداد</td>
                <td>مبلغ</td>
                <td>تخفیف</td>
                <td>مالیات</td>
                <td>تاریخ فاکتور</td>
                <td>مشتری</td>
                <td>انبار</td>
            </tr>
        </thead>
        <tbody>
            {% for item in ReceiptBuy %}
                <tr>
                    <td data-label="ردیف">{{item.Id}}</td>
                    <td data-label="کالا">{{item.IdCommodity}}</td>
                    <td data-label="واحد سنجش">{{item.IdUnitofMeasurement}}</td>
                    <td data-label="تعداد">{{item.Count}}</td>
                    <td data-label="مبلغ">{{item.Amount}}</td>
                    <td data-label="تخفیف">{{item.Discount}}</td>
                    <td data-label="مالیات">{{item.Taxation}}</td>
                    <td data-label="تاریخ فاکتور">{{item.jDate}}</td>
                    <td data-label="مشتری">{{item.IdCustomer}}</td>
                    <td data-label="انبار">{{item.IdStoreroom}}</td>
                </tr>
            {% endfor %}
        </tbody>
</table>
{% else %}
    <h2 style="text-align: center;">فاکتور فروش خالی است</h2s>
{% endif %}
<button onclick="print()" class="btn btn-info">پرینت گزارش</button>
{% endblock %}

templates/inventory/Receipt/ListReportStoreroomBuy.html
{% extends 'Template/base.html' %}
{% load humanize %}

{% block title %}{% block title-meta %}
	فاکتور انبار خرید
{% endblock %}{% endblock %}

{% block Css %}
    <link rel="stylesheet" href="https://cdn.rtlcss.com/bootstrap/v4.2.1/css/bootstrap.min.css">
    <style type="text/css">
    *{
        direction:rtl;
    }
    .SPNName{
        color:rgb(71, 67, 67);
        text-decoration: underline;
    }
    @media print{
        button,h2,.main-footer{
            display: none !important;
        }
    }
    </style>
{% endblock %}
{% block JS %}
    <!-- <script type="text/javascript">
        window.onload = print();
    </script> -->
{% endblock %}
{% block main %}
{% if ReceiptStoreroomBuy %}
    <table class="tableResponse">
        <thead>
            <tr>
                <th>ردیف</th>
                <th>کالا</th>
                <th>واحد سنجش</th>
                <th>تعداد</th>
                <th>مبلغ</th>
                <th>تخفیف</th>
                <th>مالیات</th>
                <th>تاریخ فاکتور</th>
                <th>مشتری</th>
                <th>انبار</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for item in ReceiptStoreroomBuy %}
                <tr>
                    <td data-label="ردیف">{{item.Id}}</td>
                    <td data-label="کالا">{{item.IdCommodity}}</td>
                    <td data-label="واحد سنجش">{{item.IdUnitofMeasurement}}</td>
                    <td data-label="تعداد">{{item.Count}}</td>
                    <td data-label="مبلغ">{{item.Amount}}</td>
                    <td data-label="تخفیف">{{item.Discount}}</td>
                    <td data-label="مالیات">{{item.Taxation}}</td>
                    <td data-label="تاریخ فاکتور">{{item.jDate}}</td>
                    <td data-label="مشتری">{{item.IdCustomer}}</td>
                    <td data-label="انبار">{{item.IdStoreroom}}</td>
                    <td data-label="">{{item.AmountAfter}}</td>
                </tr>
            {% endfor %}
        </tbody>
        <tr>
            <td colspan="10">جمع کل</td>
            <td>{{ReceiptStoreroomBuyPrice}}</td>
        </tr>
</table>
{% else %}
    <h2 style="text-align: center;">فاکتور فروش خالی است</h2s>
{% endif %}
<button onclick="print()" class="btn btn-info">پرینت گزارش</button>
{% endblock %}

templates/inventory/Receipt/confirm_delete.html
{% extends 'Template/base.html' %}

{% block title %}{% block title-meta %}
	حذف فاکتور
{% endblock %}{% endblock %}

{% block main %}
<div class="col-md-8 text-center mx-auto">
  <div class="card card-danger">
    <div class="card-header">
      <h3 class="card-title mb-0 float-left">حذف فاکتور</h3>
    </div>
		<div class="card-body py-4">
			<form method="post">{% csrf_token %}
			    <p class="py-2">
					کاربر آقا/خانم
					«
						{% if user.get_full_name %}
							{{user.get_full_name}}
						{% else %}
							{{user.username}}
						{% endif %}
					»
					عزیز، آیا از حذف فاکتور با نام
					 « {{object}} »
					 مطمئن هستید؟</p>
			    <input type="submit" value="حذف" class="btn btn-danger">
			</form>
		</div>
</div>
{% endblock %}

templates/inventory/Receipt/create-update.html
{% extends 'Template/base.html' %}
{% load crispy_forms_tags %}

{% block main %}
<div class="col-md-12">
	<div class="card card-primary">
		<div class="card-header">
			<h3 class="card-title mb-0 float-left">تعریف فاکتور</h3>
		</div>
		<div class="card-body">
			<form method="post" enctype="multipart/form-data">{% csrf_token %}
				<div class="row">
					<div class="col-sm-4 col-md-4 col-lg-4">
						{{ form.IdCommodity|as_crispy_field }}
					</div>
					<div class="col-sm-4 col-md-4 col-lg-4">
						{{ form.IdUnitofMeasurement|as_crispy_field }}
					</div>
					<div class="col-sm-4 col-md-4 col-lg-4">
						{{ form.Count|as_crispy_field }}
					</div>
					<div class="col-sm-4 col-md-4 col-lg-4">
						{{ form.Amount|as_crispy_field }}
					</div>
					<div class="col-sm-4 col-md-4 col-lg-4">
						{{ form.Discount|as_crispy_field }}
					</div>
					<div class="col-sm-4 col-md-4 col-lg-4">
						{{ form.Taxation|as_crispy_field }}
					</div>
					<div class="col-sm-4 col-md-4 col-lg-4">
						{{ form.Type|as_crispy_field }}
					</div>
					<div class="col-sm-4 col-md-4 col-lg-4">
						{{ form.IdCustomer|as_crispy_field }}
					</div>
					<div class="col-sm-4 col-md-4 col-lg-4">
						{{ form.IdStoreroom|as_crispy_field }}
					</div>
				</div>
				<button class="btn btn-success">ثبت فاکتور</button>
				{% if user.is_superuser and item.pk %}
				<a class="badge text-danger" href="{% url 'inventory:Receipt-Delete' item.pk %}">حذف</a>
				{% endif %}
			</form>
		</div>
</div>
{% endblock %}

templates/inventory/Receipt/list.html
{% extends 'Template/base.html' %}

{% block title %}{% block title-meta %}
	لیست فاکتور خرید/فروش
{% endblock %}{% endblock %}

{% block Create %}
    <a class="badge text-primary" href="{% url 'inventory:Receipt-Create' %}">تعریف فاکتور</a>
{% endblock %}


{% block main %}
    {% if object_list %}
    <table class="tableResponse">
        <thead>
            <tr>
                <th>ردیف</th>
                <th>کالا</th>
                <th>واحد سنجش</th>
                <th>تعداد</th>
                <th>مبلغ</th>
                <th>تخفیف</th>
                <th>مالیات</th>
                <th>تاریخ فاکتور</th>
                <th>مشتری</th>
                <th>انبار</th>
                <th>نوع</th>
                <th>عملیات</th>
            </tr>
        </thead>
        <tbody>
        {% for item in object_list %}
            <tr>
                <td data-label="ردیف">{{item.Id}}</td>
                <td data-label="کالا">{{item.IdCommodity}}</td>
                <td data-label="واحد سنجش">{{item.IdUnitofMeasurement}}</td>
                <td data-label="تعداد">{{item.Count}}</td>
                <td data-label="مبلغ">{{item.Amount}}</td>
                <td data-label="تخفیف">{{item.Discount}}</td>
                <td data-label="مالیات">{{item.Taxation}}</td>
                <td data-label="تاریخ فاکتور">{{item.jDate}}</td>
                <td data-label="مشتری">{{item.IdCustomer}}</td>
                <td data-label="انبار">
                    {% if item.Type == 'B' %}
                        <a href="{% url 'inventory:Receipt-ReportStoreroomBuy' item.IdStoreroom.Id %}" target="_blank">
                            {{item.IdStoreroom}}
                        </a>
                    {% elif item.Type == 'S' %}
                        <a href="{% url 'inventory:Receipt-ReportStoreroomSale' item.IdStoreroom.Id %}" target="_blank">
                            {{item.IdStoreroom}}
                        </a>
                    {% endif %}
                </td>
                <td data-label="نوع">
                    {% if item.Type == 'B' %}
                        <p>خرید</p>
                    {% elif item.Type == 'S' %}
                        <p>فروش</p>
                    {% endif %}
                </td>
                <td data-label="عملیات">
                    {% if user.is_superuser or user.is_storekeeper %}
                    <a class="badge text-danger" href="{% url 'inventory:Receipt-Delete' item.pk %}">حذف</a>
                    <a class="badge text-succsess" href="{% url 'inventory:Receipt-update' item.pk %}">ویرایش</a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="row pagination">
        <span class="step-links">
            {% if is_paginated %}
                {% if page_obj.has_previous %}
                    <a class="btn btn-primary" href="{% url 'inventory:homeRE' page_obj.previous_page_number %}">
                        قبلی
                    </a>
                {% endif %}
                {% if page_obj.has_next %}
                    <a class="btn btn-primary" href="{% url 'inventory:homeRE' page_obj.next_page_number %}">
                        بعدی
                    </a>
                {% endif %}
            {% endif %}
        </span>
    </div>
    {% else %}
    <div style="min-height:200px;">
        <P class="text-center">
            لیست فاکتور خالی است
            <br>
            <a href="{% url 'inventory:Receipt-Create' %}">
                تعریف فاکتور
            </a>
        </P>
    </div>
    {% endif %}
{% endblock %}